// constants/madrid_venues.ts

export const MADRID_VENUES = [
  {
    id: 'acid_cafe',
    name: 'Acid Café',
    neighborhood: 'Lavapiés',
    description: '',
    tags: ['cafe', 'coffee', 'Lavapiés'],
  },
  {
    id: 'plenti',
    name: 'Plenti',
    neighborhood: 'Lavapiés',
    description: '',
    tags: ['cafe', 'brunch', 'Lavapiés'],
  },
  {
    id: 'hola_coffee',
    name: 'Hola Coffee',
    neighborhood: 'Lavapiés',
    description: '',
    tags: ['coffee roastery', 'Lavapiés'],
  },
  {
    id: 'cafes_el_magistral',
    name: 'Cafés El Magistral',
    neighborhood: 'Lavapiés',
    description: '',
    tags: ['coffee roastery', 'Lavapiés'],
  },
  {
    id: 'la_faneka',
    name: 'La Faneka',
    neighborhood: 'Lavapiés',
    description: '',
    tags: ['bakery', 'Lavapiés'],
  },
  {
    id: 'la_encomienda',
    name: 'La Encomienda',
    neighborhood: 'Lavapiés',
    description: '',
    tags: ['vegan', 'restaurant', 'Lavapiés'],
  },
  {
    id: 'cafes_tornado',
    name: 'Cafés Tornado',
    neighborhood: 'Lavapiés',
    description: '',
    tags: ['coffee roastery', 'Lavapiés'],
  },
  {
    id: 'lopez_bar',
    name: 'López Bar',
    neighborhood: 'Lavapiés',
    description: '',
    tags: ['bar', 'Lavapiés'],
  },
  {
    id: 'la_chingada',
    name: 'La Chingada',
    neighborhood: 'Lavapiés',
    description: '',
    tags: ['mexican', 'restaurant', 'Lavapiés'],
  },
  {
    id: 'la_pistola',
    name: 'La Pistola',
    neighborhood: 'Lavapiés',
    description: '',
    tags: ['bar', 'Lavapiés'],
  },
  {
    id: 'ruda_cafe',
    name: 'Ruda Café',
    neighborhood: 'La Latina',
    description: '',
    tags: ['cafe', 'La Latina'],
  },
  {
    id: 'cafe_del_nuncio',
    name: 'Café del Nuncio',
    neighborhood: 'La Latina',
    description: '',
    tags: ['cafe', 'La Latina'],
  },
  {
    id: 'jimmy_barnatan',
    name: 'Jimmy Barnatán',
    neighborhood: 'La Latina',
    description: '',
    tags: ['bar', 'music', 'La Latina'],
  },
  {
    id: 'la_palma_60',
    name: 'La Palma 60',
    neighborhood: 'Malasaña',
    description: '',
    tags: ['gallery', 'Malasaña'],
  },
  {
    id: 'molar_disco_bar_libreria',
    name: 'Molar: Disco Bar Librería',
    neighborhood: 'La Latina',
    description: '',
    tags: ['record shop', 'bookshop', 'bar', 'La Latina'],
  },
  {
    id: 'arrebato_libros',
    name: 'Arrebato Libros',
    neighborhood: 'Malasaña',
    description: '',
    tags: ['bookshop', 'Malasaña'],
  },
  {
    id: 'tipos_infames',
    name: 'Tipos Infames',
    neighborhood: 'Malasaña',
    description: '',
    tags: ['bookshop', 'wine bar', 'Malasaña'],
  },
  {
    id: 'anton_martin_market',
    name: 'Antón Martín Market',
    neighborhood: 'Lavapiés',
    description: '',
    tags: ['market', 'Lavapiés'],
  },
  {
    id: 'sala_equis',
    name: 'Sala Equis',
    neighborhood: 'Centro',
    description: '',
    tags: ['cinema', 'bar', 'Centro'],
  },
  {
    id: 'cine_dore',
    name: 'Cine Doré',
    neighborhood: 'Lavapiés',
    description: '',
    tags: ['cinema', 'Lavapiés'],
  },
  {
    id: 'matadero_madrid',
    name: 'Matadero Madrid',
    neighborhood: 'Arganzuela',
    description: '',
    tags: ['cultural center', 'Arganzuela'],
  },
  {
    id: 'el_rastro',
    name: 'El Rastro',
    neighborhood: 'La Latina',
    description: '',
    tags: ['market', 'La Latina'],
  },
  {
    id: 'rio_manzanares_walk',
    name: 'Río Manzanares Walk',
    neighborhood: 'Arganzuela',
    description: '',
    tags: ['walk', 'river', 'Arganzuela'],
  },
  {
    id: 'templo_de_debod',
    name: 'Templo de Debod',
    neighborhood: 'Argüelles',
    description: '',
    tags: ['park', 'viewpoint', 'Argüelles'],
  },
  {
    id: 'retiro_park',
    name: 'Retiro Park',
    neighborhood: 'Retiro',
    description: '',
    tags: ['park', 'Retiro'],
  },
  {
    id: 'parque_del_oeste',
    name: 'Parque del Oeste',
    neighborhood: 'Argüelles',
    description: '',
    tags: ['park', 'Argüelles'],
  },
  {
    id: 'museo_del_prado',
    name: 'Museo del Prado',
    neighborhood: 'Jerónimos',
    description: '',
    tags: ['museum', 'Jerónimos'],
  },
  {
    id: 'museo_reina_sofia',
    name: 'Museo Reina Sofía',
    neighborhood: 'Atocha',
    description: '',
    tags: ['museum', 'Atocha'],
  },
  {
    id: 'museo_thyssen_bornemisza',
    name: 'Museo Thyssen-Bornemisza',
    neighborhood: 'Paseo del Prado',
    description: '',
    tags: ['museum', 'Paseo del Prado'],
  },
  {
    id: 'caixaforum_madrid',
    name: 'CaixaForum Madrid',
    neighborhood: 'Paseo del Prado',
    description: '',
    tags: ['museum', 'Paseo del Prado'],
  },
  {
    id: 'museo_sorolla',
    name: 'Museo Sorolla',
    neighborhood: 'Chamberí',
    description: '',
    tags: ['museum', 'Chamberí'],
  },
  {
    id: 'circulo_de_bellas_artes',
    name: 'Círculo de Bellas Artes',
    neighborhood: 'Centro',
    description: '',
    tags: ['cultural center', 'Centro'],
  },
];
